### PR TITLE
move_table checked upto the 1st 300 moves

### PR DESCRIPTION
**Pull request by rickonstarked**
submission should have 25% recoil, dunno where to put it
struggle should have 25% max hp recoil
beat up has new mechanics

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Don't worry about recoil, it's handled by a different function in the battle system file. It's called recoil something. Thanks for the help! I'm gonna trust you and hope everything you changed is true. :D

**Comment by rickonstarked** [comment]
or you can check them yourself, these are the list of bugs i found:

**payday** shouldnt make **contact**
**scatch** power should be **40**
**razor wind** should have **10pp** and targets **both opp**
**whirlwind** shouldnt check acc
**stomp** has wrong battle script
**bite** eff chance should be **30%**
**roar** shouldnt check acc
**acid** power should be **40**
**aurora beam** has wrong battle script and should **lower atk**
**counter** should be affected by **protect** and make **contact**
**razor leaf** should taget **both opp**
**minimize** should **sharply lower evasion**
**barrier** should  **sharply increase defense**
**bide** shouldnt check acc and should be **physical**
**smog** should be **special**
**bone club** has wrong battlescript
**waterfall** already flinches so shouldnt be affected by **king's rock**
**poison gas** should taget **both opp**
**barrage** has wrong battlescript
**hyper fang** eff chance should be **10%**
**Sharpen** has wrong battlescript
**struggle** shouldnt check acc
**spider web** shouldnt check acc
**mind reader** shouldnt check acc
**snore** already flinches so shouldnt be affected by **king's rock**
**conversion 2** has wrong battlescript
**cotton spore** should taget **both opp**
**feint attack** should make contact
**foresight** shouldnt check acc
**destiny bond** should be a **status move**
**detect** should have 5pp
**lock on** shouldnt check acc
**giga drain** power should be **75** and has **10pp**
**milk drink** should only be affected by **snatch**
**steel wing** should **raise defence**
**mean look** shouldnt check acc
**pain split** shouldnt check acc
**vital throw** shouldnt check acc
**twister** should be **special** and it already flinches so shouldnt be affected by **king's rock**
**mirror coat** should be **special** and affected by **protect**
**extremespeed** should have **+2 priority**
**future sight** should have **10pp**
**whirlpool** power should be **35** and has **85% acc**
**stockpile** should have **20pp**
**spit up** should be **special**
**heatwave** power should be **95** and **target both opp**
**will-o-wisp** should have **85% acc**
**smellingsalt** power should be **70**
**follow me** shouldnt check acc and should have **+2 priority**
**nature power** should be **status move**
**charge** shouldnt check acc
**helpinghand** shouldnt check acc
**role play** shouldnt check acc
**wish** shouldnt check acc and should only be affected by **snatch**
**assist** shouldnt check acc
**ingrain** shouldnt check acc and **priority got swapped with prop**
**magic coat** shouldnt check acc
**recycle** shouldnt check acc and should be affected by **snatch**
**yawn** shouldnt check acc
**skillswap** shouldnt check acc
**imprison** shouldnt check acc and should be affected by **snatch**
**refresh** shouldnt check acc
**grudge** shouldnt check acc
**Snatch** shouldnt check acc
**dive** power should be **80**
**camouflage** shouldnt check acc
**tail glow** shouldnt check acc

**Comment by KDSKardabox** [comment]
I'll manually merge your data after I finish the Mega Icon. Thanks for your contributions,

**Comment by KDSKardabox** [comment]
added your changes. thanks again!

**Pull request closed without merging**
