### PR TITLE
Added Judgement and Techno blast, fixed typo

### PR DESCRIPTION
**Pull request by Giratina-O**

### CODE REVIEW

**Comment by KDSKardabox** [comment]
you need to add defines for plates in the item_effect.h file too

**Comment by KDSKardabox** [comment]
Please make sure that the code compiles before submitting pull request. I have corrected them for now.

**Comment by DizzyEggg** [comment]
Why did you merge it? Now we need 17 effects for plates and 17 effects for type raising items(blackglasses, etc.) I think we could handle it differently.

**Comment by rickonstarked** [comment]
though i dunno how to do it but i think you could use the extra section in item to check if it is a plate. same for drives so you can have 1 drive with diff types. so for case1 movetype=water.. etc. =D

**Pull request merged**
